### ISSUE TITLE
数据

### ISSUE THREAD

**Issue by wangxinzhe123** [dair-iitd/DSRE#1]
您好，请问如果使用自己的数据集只有一种关系，即每对实体e1和e2之间只有一种关系r，该代码是否是适用的呢？

**Comment by rathorevipul28** [comment]
Yes, this code works even when there is only one relation between entities e1 and e2, and it can handle the 'NA' class as well!

**Comment by wangxinzhe123** [comment]
Because the maximum number of tokens allowed to be entered by bert is 512, but the length of the connected statements in my bag exceeds 512. If I don't want to discard the data after 512 bits, is there a solution to this situation?
(因为bert允许输入的最大tokens数目为512，但我bag中的语句连接之后长度超过512，如果我不想舍弃512位之后的数据，请问这种情况有解决办法吗？)

**Comment by rathorevipul28** [comment]
Even in our case, the length of combined sentences exceeded 512. But we showed in our paper that this doesn't hurt the performance compared to the baseline models. 
But you can try other encoders like AllenNLP's longformer (https://github.com/allenai/longformer) supporting upto 16k tokens in the sequence. 
Also checkout Transformer XL (https://github.com/kimiyoung/transformer-xl).

**Comment by wangxinzhe123** [comment]
好的，非常感谢

**Comment by wangxinzhe123** [comment]
能否再详细解释下论文中的这句话： Second, in principle, the model
may be able to relax a part of the at-least-one assumption. For example, if no sentence individually
expresses a relation, but if multiple facts in different sentences collectively predict the relation, our
model may be able to learn to extract that.
