### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by wangxinzhe123** [dair-iitd/DSRE#2]
能否再详细解释下论文中的这句话： "Second, in principle, the model
may be able to relax a part of the at-least-one assumption. For example, if no sentence individually
expresses a relation, but if multiple facts in different sentences collectively predict the relation, our
model may be able to learn to extract that."

**Comment by rathorevipul28** [comment]
Intra-bag attention models assume there is at least one sentence expressing the relation between 2 entities in a bag.
But there might be cases like: s1: A is the father of B, s2: B is the sibling of C.
What is the relation between A and C?

In this example, intra-bag attention models will process each sentence separately and may not be able to capture FatherOf relation between A and C. But PARE which sees all these sentences as a sequence can be able to do that.

**Comment by wangxinzhe123** [comment]
Well, thank you very much.
